### ISSUE TITLE
terraform plan always update bandwidth

### ISSUE THREAD

**Issue by senare** [norrland/terraform-provider-glesys#9]
Seams that there are some issue / confusion with bandwidth also ?

I spec it as 100 but even so it want's to update it every time.
```
Terraform will perform the following actions:

  # glesys_server.head-master will be updated in-place
  ~ resource "glesys_server" "head-master" {
      ~ bandwidth    = 0 -> 100
        cpu          = 1
        datacenter   = "Falkenberg"

```

I also have to admit not having looked into this in detail (... at-least not yet )

**Comment by norrland** [comment]
Hi,
If you check the /server/details for a KVM host, you'll see that the value for bandwidth is null/None (depending on language).

For now you can work around this with
```
resource "glesys_server" "myserver" {
  ...

  lifecycle {
    ignore_changes = [
      bandwidth,
    ]
  }
}
```
